export const QUIT_APPLICATION_CHANNEL = 'QUIT_APPLICATION_CHANNEL'

export interface DownloadThumbnailIpcResponse {
    dataUrl?: string
    expiration?: number
}

export const EXAMPLE_CHANNEL = 'EXAMPLE_CHANNEL'
export const GET_SATELLITE_CONFIG_CHANNEL = 'GET_SATELLITE_CONFIG_CHANNEL'
export const SET_WALLPAPER_CHANNEL = 'SET_WALLPAPER_CHANNEL'
export const VISIBILITY_CHANGE_ALERT_CHANNEL = 'VISIBILITY_CHANGE_ALERT_CHANNEL'
export const GET_CURRENT_VIEW_CHANNEL = 'GET_CURRENT_VIEW_CHANNEL'
export const DOWNLOAD_THUMBNAIL_CHANNEL = 'DOWNLOAD_THUMBNAIL_CHANNEL'
export const GET_START_ON_LOGIN = 'GET_START_ON_LOGIN'
export const SET_START_ON_LOGIN = 'SET_START_ON_LOGIN'
export const GET_FIRST_RUN = 'GET_FIRST_RUN'
export const SET_FIRST_RUN = 'SET_FIRST_RUN'
export const OPEN_WINDOWS_ICON_SETTINGS = 'OPEN_WINDOWS_ICON_SETTINGS'
export const GET_AUTO_UPDATE = 'GET_AUTO_UPDATE'
export const SET_AUTO_UPDATE = 'SET_AUTO_UPDATE'
